# image will be published to ghcr.io/<user>/<name>
name: charoite
# description will be included in the image's metadata
description: This is my ublue based OS.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:  
      #- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/trixieua/mutter-patched/repo/fedora-%OS_VERSION%/trixieua-mutter-patched-fedora-%OS_VERSION%.repo
      #- https://copr.fedorainfracloud.org/coprs/cyrinux/misc/repo/fedora-%OS_VERSION%/cyrinux-misc-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/shdwchn10/AllTheTools/repo/fedora-%OS_VERSION%/shdwchn10-AllTheTools-fedora-%OS_VERSION%.repo
      #- https://copr.fedorainfracloud.org/coprs/principis/howdy/repo/fedora-%OS_VERSION%/principis-howdy-fedora-%OS_VERSION%.repo
      #- https://copr.fedorainfracloud.org/coprs/champe20/apx/repo/fedora-%OS_VERSION%/champe20-apx-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/fmonteghetti/keyd/repo/fedora-%OS_VERSION%/fmonteghetti-keyd-fedora-%OS_VERSION%.repo
    install:
      - keyd
      #- devmem2
      - kernel-tools
      - tailscale
      - bat
      - eza
      - fish
      - zsh
      #- intel-undervolt
      - msr-tools
      #- waydroid
      - topgrade
      ##- zenity
      - powertop
      #- howdy
      #- gcc
      - python3.11
      - adw-gtk3-theme
      #- pipx
      - rapid-photo-downloader
      - rtl-sdr
      #- gr-osmosdr
      - gqrx
      #- gnuradio 
      - sdrangel
      #- android-tools
      #- apx
      #- docker-compose
      #- rust
      #- cargo
      #- micro
      #- starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      ##- firefox
      ##- firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      
  - type: script
    scripts: 
      - gnometb.sh
      #- install_topgrade.sh
    
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
